import React from 'react';
import { motion } from 'framer-motion';
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip } from 'recharts';
import { GeneratedExam, ExamResult } from '../types';
import { RefreshCcw, Check, X, Minus, Award, Clock, Target, ListChecks, CheckCircle, Download } from 'lucide-react';
import { jsPDF } from "jspdf";

const MotionDiv = motion.div as any;

interface ResultsPageProps {
  exam: GeneratedExam;
  result: ExamResult;
  onRestart: () => void;
}

const ResultsPage: React.FC<ResultsPageProps> = ({ exam, result, onRestart }) => {
  const accuracy = result.totalQuestions > 0 ? Math.round((result.correctAnswers / (result.correctAnswers + result.wrongAnswers)) * 100) : 0;
  const percentage = Math.round((result.correctAnswers / result.totalQuestions) * 100);

  const topicAnalysis = exam.questions.reduce((acc, q) => {
    const isCorrect = result.answers[q.id] === q.correctAnswerIndex;
    if (!acc[q.topic]) acc[q.topic] = { total: 0, correct: 0 };
    acc[q.topic].total += 1;
    if (isCorrect) acc[q.topic].correct += 1;
    return acc;
  }, {} as Record<string, { total: number; correct: number }>);

  const barData = Object.keys(topicAnalysis).map(topic => ({
    name: topic.length > 12 ? topic.substring(0, 12) + '...' : topic,
    score: Math.round((topicAnalysis[topic].correct / topicAnalysis[topic].total) * 100)
  }));

  const handleDownloadPDF = () => {
    // Standard ES Module usage for Vercel/Vite build
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const maxLineWidth = pageWidth - margin * 2;
    let yPos = 20;

    // --- Header ---
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text(exam.title, margin, yPos);
    yPos += 8;
    
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`Candidate: ${exam.config.candidateName || 'N/A'} | Generated by Note2Exam`, margin, yPos);
    yPos += 6;
    doc.text(`Date: ${new Date().toLocaleDateString()} | Score: ${result.score}/${result.totalQuestions}`, margin, yPos);
    
    // Draw a line
    yPos += 5;
    doc.setLineWidth(0.5);
    doc.line(margin, yPos, pageWidth - margin, yPos);
    yPos += 10;

    // --- Questions ---
    doc.setFontSize(12);
    exam.questions.forEach((q, i) => {
        // Page break check (approximate height of a question block)
        if (yPos > 260) { doc.addPage(); yPos = 20; }

        doc.setFont("helvetica", "bold");
        const qTitle = `Q${i + 1}. ${q.text}`;
        const splitTitle = doc.splitTextToSize(qTitle, maxLineWidth);
        doc.text(splitTitle, margin, yPos);
        yPos += (splitTitle.length * 5) + 2;

        doc.setFont("helvetica", "normal");
        q.options.forEach((opt, optIdx) => {
             // Page break check for options
             if (yPos > 280) { doc.addPage(); yPos = 20; }
             
             const optText = `   (${String.fromCharCode(65 + optIdx)}) ${opt}`;
             const splitOpt = doc.splitTextToSize(optText, maxLineWidth);
             doc.text(splitOpt, margin, yPos);
             yPos += (splitOpt.length * 5) + 1;
        });
        yPos += 6; // Spacing between questions
    });

    // --- Answer Key Page ---
    doc.addPage();
    yPos = 20;
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("Answer Key & Explanations", margin, yPos);
    yPos += 15;

    doc.setFontSize(10);
    exam.questions.forEach((q, i) => {
        if (yPos > 250) { doc.addPage(); yPos = 20; }
        
        doc.setFont("helvetica", "bold");
        doc.setTextColor(0, 0, 0);
        doc.text(`Q${i + 1}: Option ${String.fromCharCode(65 + q.correctAnswerIndex)}`, margin, yPos);
        yPos += 5;
        
        doc.setFont("helvetica", "italic");
        doc.setTextColor(80, 80, 80); // Dark grey for rationale
        const rationalePrefix = "Rationale: ";
        const rationaleText = q.explanation;
        const splitRat = doc.splitTextToSize(rationalePrefix + rationaleText, maxLineWidth);
        doc.text(splitRat, margin, yPos);
        yPos += (splitRat.length * 4) + 8;
    });

    doc.save(`${exam.title.replace(/\s+/g, '_')}_Exam.pdf`);
  };

  return (
    <div className="min-h-screen bg-[#f8fafc] text-slate-800 p-4 md:p-10 overflow-y-auto custom-scrollbar font-sans">
      <div className="max-w-5xl mx-auto">
        
        {/* Professional Header */}
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center mb-10 gap-6 border-b border-slate-200 pb-8">
            <div className="flex items-center gap-4">
              <div className="w-16 h-16 bg-slate-900 rounded-2xl flex items-center justify-center text-yellow-400 shadow-xl">
                 <Award className="w-8 h-8" />
              </div>
              <div>
                  <h1 className="text-3xl font-black text-slate-900 tracking-tight">Official Scorecard</h1>
                  <p className="text-slate-500 font-medium text-sm">Exam: <span className="text-slate-900 font-bold">{exam.title}</span></p>
              </div>
            </div>
            
            <div className="flex items-center gap-3 w-full md:w-auto">
                <button 
                    onClick={handleDownloadPDF}
                    className="flex-1 md:flex-none px-5 py-3 bg-white border border-slate-300 text-slate-700 rounded-xl font-bold flex items-center justify-center gap-2 hover:bg-slate-50 hover:border-slate-400 transition-all shadow-sm active:scale-95"
                >
                    <Download className="w-4 h-4" />
                    <span>Download PDF</span>
                </button>
                <button 
                    onClick={onRestart} 
                    className="flex-1 md:flex-none px-6 py-3 bg-slate-900 text-white rounded-xl font-bold flex items-center justify-center gap-2 hover:bg-slate-800 transition-all shadow-lg active:scale-95"
                >
                    <RefreshCcw className="w-4 h-4" /> 
                    <span>Take Another Test</span>
                </button>
            </div>
        </div>

        {/* Core Metrics Grid */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-8">
            {[
                { label: 'Final Score', val: result.score.toFixed(1), max: `/ ${result.totalQuestions}`, icon: Target, color: 'text-slate-900', border: 'border-slate-900' },
                { label: 'Accuracy', val: `${isNaN(accuracy) ? 0 : accuracy}%`, icon: CheckCircle, color: 'text-blue-600', border: 'border-blue-500' },
                { label: 'Time Spent', val: `${Math.floor(result.timeTakenSeconds / 60)}m`, max: `${result.timeTakenSeconds % 60}s`, icon: Clock, color: 'text-blue-600', border: 'border-blue-500' },
                { label: 'Rank Estimate', val: percentage >= 70 ? 'Distinction' : percentage >= 40 ? 'Qualified' : 'Re-test', icon: ListChecks, color: 'text-yellow-600', border: 'border-yellow-500' }
            ].map((m, i) => (
                <MotionDiv key={i} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.1 }} className={`bg-white p-5 rounded-2xl border-l-4 ${m.border} shadow-sm border border-slate-200`}>
                    <div className="flex justify-between items-start mb-2">
                        <p className="text-[10px] font-black uppercase text-slate-400 tracking-widest">{m.label}</p>
                        <m.icon className="w-4 h-4 text-slate-300" />
                    </div>
                    <h3 className={`text-2xl font-black ${m.color}`}>
                        {m.val} <span className="text-sm font-bold text-slate-400">{m.max}</span>
                    </h3>
                </MotionDiv>
            ))}
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-12">
            {/* Response Breakdown Box */}
            <div className="bg-white p-8 rounded-3xl border border-slate-200 shadow-sm flex flex-col justify-center">
                <h3 className="text-sm font-black text-slate-400 uppercase tracking-[0.2em] mb-8">Response Breakdown</h3>
                <div className="grid grid-cols-3 gap-4 h-full items-center">
                    <div className="flex flex-col items-center p-4 bg-blue-50 rounded-2xl border border-blue-100">
                        <CheckCircle className="w-6 h-6 text-blue-500 mb-2" />
                        <span className="text-3xl font-black text-blue-600">{result.correctAnswers}</span>
                        <span className="text-[10px] font-bold text-blue-400 uppercase tracking-wider mt-1">Correct</span>
                    </div>
                    <div className="flex flex-col items-center p-4 bg-red-50 rounded-2xl border border-red-100">
                        <X className="w-6 h-6 text-red-500 mb-2" />
                        <span className="text-3xl font-black text-red-600">{result.wrongAnswers}</span>
                        <span className="text-[10px] font-bold text-red-400 uppercase tracking-wider mt-1">Wrong</span>
                    </div>
                    <div className="flex flex-col items-center p-4 bg-slate-50 rounded-2xl border border-slate-100">
                        <Minus className="w-6 h-6 text-slate-400 mb-2" />
                        <span className="text-3xl font-black text-slate-600">{result.skippedAnswers}</span>
                        <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider mt-1">Skipped</span>
                    </div>
                </div>
            </div>

            {/* Topic Proficiency Box */}
            <div className="bg-white p-8 rounded-3xl border border-slate-200 shadow-sm">
                <h3 className="text-sm font-black text-slate-400 uppercase tracking-[0.2em] mb-8">Topic Proficiency</h3>
                <div className="h-56 w-full">
                     <ResponsiveContainer width="100%" height="100%">
                        <BarChart data={barData} layout="vertical" margin={{ left: -10 }}>
                            <XAxis type="number" domain={[0, 100]} hide />
                            <YAxis dataKey="name" type="category" width={100} tick={{fill: '#94a3b8', fontSize: 10, fontWeight: 'bold'}} />
                            <Tooltip cursor={{ fill: '#f1f5f9' }} />
                            <Bar dataKey="score" fill="#eab308" radius={[0, 4, 4, 0]} barSize={24} />
                        </BarChart>
                     </ResponsiveContainer>
                </div>
            </div>
        </div>

        {/* Review Table Section */}
        <div className="space-y-6">
            <div className="flex items-center gap-3">
              <div className="w-1.5 h-8 bg-slate-900 rounded-full" />
              <h3 className="text-2xl font-black text-slate-900">Post-Exam Review</h3>
            </div>
            
            <div className="space-y-4">
                {exam.questions.map((q, idx) => {
                    const userAnswer = result.answers[q.id];
                    const isCorrect = userAnswer === q.correctAnswerIndex;
                    const isSkipped = userAnswer === undefined;
                    
                    return (
                        <div key={q.id} className={`group bg-white p-6 md:p-8 rounded-2xl border transition-all ${isCorrect ? 'border-blue-100 hover:border-blue-300' : isSkipped ? 'border-slate-100' : 'border-red-100 hover:border-red-300'}`}>
                            <div className="flex flex-col md:flex-row gap-6">
                                <div className="flex-1">
                                    <div className="flex items-center gap-3 mb-4">
                                        <span className={`w-8 h-8 shrink-0 rounded-xl flex items-center justify-center text-xs font-black border-2 ${isCorrect ? 'bg-blue-50 border-blue-200 text-blue-600' : isSkipped ? 'bg-slate-50 border-slate-200 text-slate-400' : 'bg-red-50 border-red-200 text-red-600'}`}>
                                            {idx + 1}
                                        </span>
                                        <p className="text-base font-bold text-slate-800">{q.text}</p>
                                    </div>
                                    
                                    <div className="grid grid-cols-1 md:grid-cols-2 gap-3 mb-6">
                                        {q.options.map((opt, optIdx) => {
                                            const isThisCorrect = optIdx === q.correctAnswerIndex;
                                            const isThisUserSelection = optIdx === userAnswer;
                                            
                                            let badge = "border-slate-100 bg-slate-50 text-slate-500";
                                            if (isThisCorrect) {
                                                // If skipped, use Green. If answered/wrong, use Blue (as per previous request).
                                                if (isSkipped) {
                                                    badge = "border-green-200 bg-green-50 text-green-700 font-bold";
                                                } else {
                                                    badge = "border-blue-200 bg-blue-50 text-blue-700 font-bold";
                                                }
                                            }
                                            else if (isThisUserSelection) {
                                                badge = "border-red-200 bg-red-50 text-red-700 font-bold";
                                            }
                                            
                                            return (
                                                <div key={optIdx} className={`px-4 py-3 rounded-xl border text-sm flex items-center justify-between ${badge}`}>
                                                    <span>{opt}</span>
                                                    {isThisCorrect && <Check className="w-4 h-4" />}
                                                    {isThisUserSelection && !isThisCorrect && <X className="w-4 h-4" />}
                                                </div>
                                            )
                                        })}
                                    </div>

                                    <div className="p-4 bg-slate-50 border border-slate-200 rounded-xl relative overflow-hidden">
                                        <div className="flex justify-between items-start mb-2">
                                            <div className="flex items-center gap-2 text-[10px] font-black text-slate-400 uppercase tracking-widest">
                                                Rationale
                                            </div>
                                        </div>
                                        <p className="text-sm text-slate-600 leading-relaxed font-medium">{q.explanation}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    )
                })}
            </div>
        </div>

        <footer className="mt-20 py-10 text-center border-t border-slate-200">
             <p className="text-slate-800 text-[11px] font-bold uppercase tracking-[0.3em] opacity-100">
                End of Report
            </p>
        </footer>
      </div>
    </div>
  );
};

export default ResultsPage;
